# Generated by Django 4.1.3 on 2022-11-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.type')),
            ],
        ),
    ]
