# Generated by Django 4.1.3 on 2022-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
