# Generated by Django 4.1.3 on 2022-12-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ad_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.type'),
        ),
    ]
